"""empty message

Revision ID: 77ff8144c66d
Revises: 20933a1f6e16
Create Date: 2021-11-08 18:46:27.896895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ff8144c66d'
down_revision = '20933a1f6e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingredient_kitchen', table_name='ingredient')
    op.create_index(op.f('ix_ingredient_kitchen'), 'ingredient', ['kitchen'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_kitchen'), table_name='ingredient')
    op.create_index('ix_ingredient_kitchen', 'ingredient', ['kitchen'], unique=False)
    # ### end Alembic commands ###
